- hosts: floatingIP2
  sudo: true
  gather_facts: no
  tasks:
  - name: Commands to allow SSH from specific machine
    shell: sudo iptables -A INPUT -p tcp -s 15.15.15.0/24 --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
  - shell: sudo iptables -A OUTPUT -p tcp --sport 22 -m conntrack --ctstate ESTABLISHED -j ACCEPT
