- hosts: floatingIP
  sudo: true
  gather_facts: no
  tasks:
  - name: 1-Verify LDAPs
    shell: ldapsearch -x -LLL -h host.example.com -D user -w password -b"dc=ad,dc=example,dc=com" -s sub "(objectClass=user)" givenName
  
  - name: 2-verify /etc/sudoers file 
    shell: cat /etc/sudoers | grep techops_dba
    register: sudoers_file
  - debug: var=sudoers_file 
  
  - name: 2-verify /etc/security/access.conf
    shell: cat /etc/security/access.conf
    register: access_conf
  - debug: var=access_conf
  
  - name: 3-get NTP startum value 
    shell: ntpdc -c sysinfo 
    register: result
  - debug: var=result 
   
  - name: 4-ping
    shell: ping -c 10 xxxxxx (second host IP)
    register: ping 
  - debug: var=ping 
